import React, { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Bot, Check, ChevronRight, FileText, Link2, LockKeyhole, ReceiptText, Send, Sparkles, Upload, WalletCards } from "lucide-react";
import "./styles.css";
import "./feedback.css";
import "./branding.css";

const rupees = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const palette=["#F2A365","#8AA7E8","#A88FDD","#54B99B","#E2C96F","#D7838A"];
const quickEntries = [{who:"Ayush",what:"Samose",amount:50,time:"10:05",status:"confirmed"},{who:"Deepesh",what:"Petrol",amount:210,time:"13:18",status:"confirmed"},{who:"Vishal",what:"Food",amount:600,time:"15:42",status:"confirmed"},{who:"Anuj",what:"Stay",amount:200,time:"18:30",status:"confirmed"}];
const demos = [{name:"Quick split",copy:"4 friends · ₹1,060",active:true},{name:"Flatmates",copy:"Rent & groceries"},{name:"Goa trip",copy:"Receipts & corrections"},{name:"Hostel floor",copy:"Hinglish & bills"}];

function settle(totals){const creditors=Object.entries(totals).filter(([,n])=>n>.01).map(([name,value])=>({name,value}));const debtors=Object.entries(totals).filter(([,n])=>n<-.01).map(([name,value])=>({name,value:-value}));const payments=[];while(creditors.length&&debtors.length){creditors.sort((a,b)=>b.value-a.value);debtors.sort((a,b)=>b.value-a.value);const amount=Math.min(creditors[0].value,debtors[0].value);payments.push([debtors[0].name,creditors[0].name,amount]);creditors[0].value-=amount;debtors[0].value-=amount;if(creditors[0].value<.01)creditors.shift();if(debtors[0].value<.01)debtors.shift()}return payments}
function buildLedger(entries, names){const confirmed=entries.filter(e=>e.status==="confirmed"&&e.amount>0);const totals=Object.fromEntries(names.map(n=>[n,0]));confirmed.forEach(e=>{const split=e.split?.length?e.split:names;totals[e.who]=(totals[e.who]||0)+e.amount;split.forEach(n=>totals[n]=(totals[n]||0)-e.amount/split.length)});return {entries,people:names.map((name,index)=>({name,paid:confirmed.filter(e=>e.who===name).reduce((sum,e)=>sum+e.amount,0),net:totals[name]||0,color:palette[index%palette.length]})),total:confirmed.reduce((sum,e)=>sum+e.amount,0),payments:settle(totals)}}
const quickLedger=buildLedger(quickEntries,["Ayush","Anuj","Deepesh","Vishal"]);
function parseChat(raw){const pattern=/^\[?(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}),?\s+(\d{1,2}:\d{2}(?:\s?[AP]M)?)\]?\s*(?:[-–]\s*)?([^:\]]+):\s*(.*)$/i;return raw.split(/\r?\n/).map(line=>line.match(pattern)).filter(Boolean).map(match=>({date:match[1],time:match[2],sender:match[3].trim(),text:match[4].trim()}))}
function extractLedger(raw,result){const messages=parseChat(raw);const names=[...new Set(messages.map(m=>m.sender))];const extracted=result.entries.map(item=>{const source=messages[item.source_message_index]||{};return {who:item.payer,what:item.description||"Shared expense",amount:typeof item.amount==="number"?item.amount:0,time:source.time||"—",status:item.confidence==="confirmed"&&item.amount?"confirmed":"pending",split:item.split_with?.filter(name=>names.includes(name))||[],evidence:item.evidence}}).filter(entry=>entry.who&&names.includes(entry.who));return buildLedger(extracted,names)}

function App(){
 const [open,setOpen]=useState(false); const [tab,setTab]=useState("overview"); const [selected,setSelected]=useState("Quick split"); const [ledger,setLedger]=useState(quickLedger); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 const total=ledger.total;
 const pending=ledger.entries.filter(entry=>entry.status==="pending");
 const selectDemo=(name)=>{setSelected(name);setLedger(quickLedger);setOpen(true);setTab("overview");setError("")};
 const handleChat=async event=>{const file=event.target.files?.[0];if(!file)return;setLoading(true);setError("");try{const raw=await file.text();const response=await fetch("/api/extract",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat:raw})});const result=await response.json();if(!response.ok)throw new Error(result.error||"We couldn't read that chat.");const next=extractLedger(raw,result);if(!next.entries.length)throw new Error("No supported shared expenses found.");setLedger(next);setSelected(file.name.replace(/\.[^.]+$/,""));setOpen(true);setTab("overview")}catch(problem){setError(problem.message)}finally{setLoading(false)}};
 const readDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
 const handleReceipt=async event=>{const file=event.target.files?.[0];if(!file)return;setLoading(true);setError("");try{if(file.size>5*1024*1024)throw new Error("Choose a receipt image under 5 MB.");const imageUrl=await readDataUrl(file);const response=await fetch("/api/receipt",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imageUrl})});const receipt=await response.json();if(!response.ok)throw new Error(receipt.error||"Unable to scan this receipt.");if(!receipt.is_receipt)throw new Error("That image does not look like a receipt.");setNotice(receipt.amount ? `Receipt verified: ${rupees.format(receipt.amount)}${receipt.merchant ? ` · ${receipt.merchant}` : ""}` : "Receipt found — please check the total.");}catch(problem){setError(problem.message)}finally{setLoading(false)}};
 const handleVoice=async event=>{const file=event.target.files?.[0];if(!file)return;setLoading(true);setError("");try{if(file.size>8*1024*1024)throw new Error("Choose a voice note under 8 MB.");const audioUrl=await readDataUrl(file);const response=await fetch("/api/transcribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({audioUrl})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to read this voice note.");setNotice(`Voice note transcribed: “${result.text}”`);}catch(problem){setError(problem.message)}finally{setLoading(false)}};
 const confirmEntry=entry=>{const resolved=ledger.entries.map(item=>item===entry?{...item,status:"confirmed"}:item);setLedger(buildLedger(resolved,ledger.people.map(person=>person.name)));setNotice("Confirmed — the settle-up has been recalculated.");};
 const summaryText=`ChatLedger · ${selected}\nTotal shared spend: ${rupees.format(ledger.total)}\n\n${ledger.payments.map(([from,to,amount])=>`• ${from} pays ${to} ${rupees.format(amount)}`).join("\n")}\n\nEveryone is square after these payments.`;
 const shareSummary=async()=>{try{const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#193630"/><circle cx="1090" cy="88" r="160" fill="#d9fb70"/><text x="72" y="100" fill="#d9fb70" font-family="Arial" font-size="28" font-weight="700">CHATLEDGER</text><text x="72" y="175" fill="white" font-family="Georgia" font-size="64">Settle-up summary</text><text x="72" y="223" fill="#b6c9c3" font-family="Arial" font-size="24">${selected}</text><text x="72" y="326" fill="white" font-family="Georgia" font-size="70">${rupees.format(ledger.total)}</text>${ledger.payments.map(([from,to,amount],index)=>`<text x="72" y="${440+index*46}" fill="white" font-family="Arial" font-size="25">${from}  →  ${to}   ·   ${rupees.format(amount)}</text>`).join("")}</svg>`;const file=new File([svg],"chatledger-summary.svg",{type:"image/svg+xml"});if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({title:"ChatLedger settle-up",text:summaryText,files:[file]});return}window.open(`https://wa.me/?text=${encodeURIComponent(summaryText)}`,"_blank","noopener,noreferrer");setNotice("WhatsApp opened with your settle-up summary.");}catch(problem){if(problem.name!=="AbortError")setError("Unable to open the share sheet.");}};
 const copyPayment=(from,to,amount)=>{const reminder=`UPI payment reminder: ${from}, please pay ${to} ${rupees.format(amount)} for ${selected}.`;navigator.clipboard?.writeText(reminder).catch(()=>{});setNotice("Payment reminder copied — paste it in WhatsApp or your UPI app.");};
 return <div className="app-shell">
  <header><a className="logo" href="/"><span className="logo-mark"><i/><i/><i/></span>chatledger</a><div className="secure"><span className="demo-dot"/>Demo mode · private by default</div></header>
  {!open ? <main className="landing">
   <motion.section initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} className="hero">
    <div className="kicker"><Sparkles size={14}/> THE SHARED-MONEY RESET</div>
    <h1>Who owes whom?<br/><i>Your chat already knows.</i></h1>
    <p>ChatLedger turns chaotic group conversations into a clear, fair settle-up—without manual entries or silent guesses.</p>
   </motion.section>
   <section className="launch-grid">
    <motion.article whileHover={{y:-4}} className="launch-card featured">
      <div className="card-icon glow"><WalletCards/></div><span className="overline">See it in 10 seconds</span><h2>Try the weekend split</h2><p>Four friends. Four expenses. One clean answer.</p>
      <div className="mini-people">{quickLedger.people.map(p=><span key={p.name} style={{background:p.color}}>{p.name[0]}</span>)}</div>
      <button className="primary" onClick={()=>selectDemo("Quick split")}>Show settle-up <ArrowUpRight size={17}/></button>
    </motion.article>
    <motion.article whileHover={{y:-4}} className="launch-card">
      <div className="card-icon"><Upload/></div><span className="overline">Use your own group</span><h2>Drop in a chat export</h2><p>Upload a WhatsApp <code>.txt</code> file. The ledger stays auditable from message to payment.</p>
      <label className="secondary"><FileText size={17}/>{loading?"Reading chat…":"Choose chat file"}<input hidden type="file" accept=".txt" onChange={handleChat}/></label>
      <small><LockKeyhole size={12}/> Your API key never reaches the browser</small>
    </motion.article>
   </section>{loading&&<div className="progress"><span/><b>Reading your chat</b><em>Extracting expenses and checking each split…</em></div>}{error&&<div className="error">{error}</div>}
   <div className="examples"><span>Explore examples</span>{demos.slice(1).map(d=><button key={d.name} onClick={()=>selectDemo(d.name)}>{d.name}<ChevronRight size={14}/></button>)}</div>
  </main> :
  <main className="ledger">
   <div className="ledger-top"><div><button className="back" onClick={()=>setOpen(false)}>← All demos</button><div className="kicker">GROUP LEDGER</div><h2>{selected}<span> · July 16</span></h2></div><button className="share" onClick={shareSummary}><Send size={15}/>Share to WhatsApp</button></div>
   <nav>{["overview","activity"].map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item==="overview"?"Overview":"Activity"}</button>)}<div className="proof"><ReceiptText size={14}/><label>Add receipt<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={handleReceipt}/></label><span>or</span><label>voice note<input hidden type="file" accept="audio/mpeg,audio/mp4,audio/ogg,audio/wav,audio/webm" onChange={handleVoice}/></label></div></nav>
   {notice&&<div className="notice"><Check size={15}/>{notice}<button onClick={()=>setNotice("")}>×</button></div>}{error&&<div className="error">{error}</div>}
   <AnimatePresence mode="wait">{tab==="overview"?<motion.section key="overview" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="overview">
    <div className="headline-card"><div><span className="overline">TOTAL SPEND</span><strong>{rupees.format(total)}</strong><p>{ledger.entries.filter(e=>e.status==="confirmed").length} confirmed expenses</p></div><div className="fair"><Bot size={18}/><span>Fair split found</span><b>{ledger.payments.length} payments settle everyone</b></div></div>
    {pending.length>0&&<section className="review-card"><div><span className="overline">NEEDS A HUMAN CHECK</span><h3>{pending.length} item{pending.length>1?"s":""} held back from the math</h3><p>ChatLedger found an unclear amount or split. Nothing is added until someone confirms it.</p></div>{pending.map(entry=><div className="review-item" key={entry.who+entry.what}><span><b>{entry.who}</b> · {entry.what}<small>{entry.evidence||"Amount or split needs confirmation"}</small></span><div><button className="confirm" onClick={()=>confirmEntry(entry)}>Confirm</button><button className="dispute" onClick={()=>setNotice("Kept pending — no amount was added.")}>Keep pending</button></div></div>)}</section>}
    <div className="content-grid"><section className="surface balances"><div className="section-head"><div><span className="overline">NET POSITIONS</span><h3>Where everyone stands</h3></div><span className="pill">Live</span></div>{ledger.people.map(p=><div className="person" key={p.name}><span className="avatar" style={{background:p.color}}>{p.name[0]}</span><span>{p.name}<small>paid {rupees.format(p.paid)}</small></span><b className={p.net>0?"gets":"owes"}>{p.net>0?"gets ":"owes "}{rupees.format(Math.abs(p.net))}</b></div>)}</section>
    <section className="surface settle"><div className="section-head"><div><span className="overline">SETTLE UP</span><h3>{ledger.payments.length} payments. Done.</h3></div><button className="icon-button" onClick={shareSummary} aria-label="Share summary"><Send size={16}/></button></div>{ledger.payments.map(([from,to,amount])=><div className="payment" key={from+to}><span>{from}</span><span className="line"></span><span>{to}</span><b>{rupees.format(amount)}</b><button onClick={()=>copyPayment(from,to,amount)}><Link2 size={13}/>Copy reminder</button></div>)}<div className="settled"><Check size={16}/>Everyone ends at zero</div></section></div>
   </motion.section>:<motion.section key="activity" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="surface activity"><div className="section-head"><div><span className="overline">AUDIT TRAIL</span><h3>Every amount has a source</h3></div></div>{ledger.entries.map(e=><div className="activity-row" key={e.who+e.what}><span className="time">{e.time}</span><span className="avatar">{e.who[0]}</span><span><b>{e.who}</b> paid for {e.what}</span><b>{e.amount ? rupees.format(e.amount) : "Needs check"}</b><span className={e.status==="confirmed" ? "confirmed" : "pending"}>{e.status==="confirmed" ? <span><Check size={13}/>confirmed</span> : "review"}</span></div>)}</motion.section>}</AnimatePresence>
  </main>}
  <footer><span>Built for groups who already live in WhatsApp</span><span><Bot size={13}/>GPT-5.6 extraction · deterministic math</span></footer>
 </div>
}
createRoot(document.getElementById("root")).render(<App/>);
